- hosts: all

  tasks:

  - name: "Copying jdk Software..."
    copy:
      dest: "/root"
      src: "/root/jdk-8u171-linux-x64.rpm"

  - name: "Copying Hadoop Software..."
    copy:
      dest: "/root"
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"

  - name: "Installing jdk Software..."
    command: "rpm -ivh jdk-8u171-linux-x64.rpm"
    ignore_errors: yes

  - name: "Installing Hadoop Software..."
    command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes

  # NAMENODE SETUP

- hosts: 192.168.1.5

  vars_prompt:
  - name: "NN_dir"
    private: no
    prompt: "Enter Namenode Directory"

  tasks:
    - name:
      file:
        state: directory
        path: "{{ NN_dir }}"

    - name: "hdfs"
      template:
        dest: "/etc/hadoop/hdfs-site.xml"
        src: "/root/hdfs.xml"

    - name: "core"
      template:
        dest: "/etc/hadoop/core-site.xml"
        src: "/root/core.xml"
        
    - name: "Formatting"
      shell: "echo Y | hadoop namenode -format"

    - name: "stopping namenode"
      command: "hadoop-daemon.sh stop namenode"

    - name: "start namenode"
      command: "hadoop-daemon.sh start namenode"

  # DATANODE SETUP

- hosts: 192.168.1.4

  vars_prompt:
  - name: "DN_dir"
    private: no
    prompt: "Enter Datanode Directory"

  tasks:
  - name: "hdfs-data"
    template:
      dest: "/etc/hadoop/hdfs-site.xml"
      src: "/root/hdfs-d.xml"

  - name:
    template:
      dest: "/etc/hadoop/core-site.xml"
      src: "/root/core-d.xml"

  - name: "create dir"
    file:
      state: directory
      path: "{{DN_dir}}"

  - name: "formating"
    command: "echo Y | hadoop datanode -format"
    ignore_errors: yes

  - name: "stopping datanode"
    command: "hadoop-daemon.sh stop datanode"

  - name: "start datanode"
    command: "hadoop-daemon.sh start datanode"
   
